name: my_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  file_picker: ^10.1.2
  just_audio: ^0.9.46
  image_gallery_saver_plus: ^4.0.1
  url_launcher: ^6.3.1
  path_provider: ^2.1.2
  http: ^1.3.0
  permission_handler: ^12.0.0+1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  # firebase_storage: ^11.6.5
  firebase_database: ^11.3.4
  cloud_functions: ^5.4.0
  intl: ^0.20.2
  flutter_image_compress: ^2.1.0
  # mime: ^1.0.4
  # path: ^1.8.3
  # http_parser: ^4.0.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - 'assets/Hadar_id.jpeg'
    - 'assets/Hadar&Tzviel.jpg'
    - 'assets/Hadar_Funney_Face.jpeg'
    - 'assets/Zviel.jpeg'
